import { OvertimeEntry, StaffMember } from './types';

export const INITIAL_AHMAD_ENTRIES: OvertimeEntry[] = [
  {
    id: 'ot-1',
    date: '2024-10-02',
    startTime: '18:00',
    endTime: '21:30',
    duration: 3.5,
    project: 'Core Banking Migration',
    notes: 'Database schema patch staging deployment',
  },
  {
    id: 'ot-2',
    date: '2024-10-04',
    startTime: '19:00',
    endTime: '23:00',
    duration: 4.0,
    project: 'Incident Hotfix L2',
    notes: 'Resolved transaction timeout deadlock in payment gateway',
  },
  {
    id: 'ot-3',
    date: '2024-10-06',
    startTime: '14:00',
    endTime: '17:00',
    duration: 3.0,
    project: 'Weekend Deployment Standby',
    notes: 'On-call monitoring for microservices cluster migration',
  },
];

export const INITIAL_OTHER_STAFF: StaffMember[] = [
  {
    id: 'EMP-10493',
    name: 'Elena Rostova',
    department: 'Warehouse Hub B',
    role: 'Inventory Lead',
    status: 'Submitted',
    submittedAt: '2024-10-06 14:15',
    avatar: 'ER',
    entries: [
      {
        id: 'er-1',
        date: '2024-10-01',
        startTime: '18:00',
        endTime: '22:00',
        duration: 4.0,
        project: 'Quarterly Inventory Audit',
        notes: 'INV-CYCLE-Q2: Stock discrepancy recount & audit check',
      },
      {
        id: 'er-2',
        date: '2024-10-03',
        startTime: '18:00',
        endTime: '21:30',
        duration: 3.5,
        project: 'Warehouse Automation Rollout',
        notes: 'SYS-PALLET: System re-binning barcode calibration',
      },
      {
        id: 'er-3',
        date: '2024-10-05',
        startTime: '18:00',
        endTime: '22:30',
        duration: 4.5,
        project: 'Expedited Inbound Shipment',
        notes: 'INB-CONTAINER: 3x 40ft container expedited offload',
      },
    ],
  },
  {
    id: 'EMP-10494',
    name: 'Marcus Chen',
    department: 'Fleet Logistics',
    role: 'Route Specialist',
    status: 'Pending',
    submittedAt: null,
    avatar: 'MC',
    entries: [
      {
        id: 'mc-1',
        date: '2024-10-02',
        startTime: '17:30',
        endTime: '21:00',
        duration: 3.5,
        project: 'Emergency Dispatch Routing',
        notes: 'URG-DELIV-41: Emergency medical supplies transport',
      },
      {
        id: 'mc-2',
        date: '2024-10-04',
        startTime: '18:00',
        endTime: '21:00',
        duration: 3.0,
        project: 'Severe Weather Detour Coordination',
        notes: 'ROUTE-DIVERSE: Monsoon highway detour rerouting delay',
      },
    ],
  },
  {
    id: 'EMP-10495',
    name: 'Priya Nair',
    department: 'Dispatch Control',
    role: 'Shift Controller',
    status: 'Submitted',
    submittedAt: '2024-10-05 09:12',
    avatar: 'PN',
    entries: [
      {
        id: 'pn-1',
        date: '2024-10-02',
        startTime: '06:00',
        endTime: '09:00',
        duration: 3.0,
        project: 'Early Shift Handover Bridge',
        notes: 'AM-HANDOVER: Early shift bridge during network maintenance',
      },
      {
        id: 'pn-2',
        date: '2024-10-04',
        startTime: '18:00',
        endTime: '22:30',
        duration: 4.5,
        project: 'Severe Storm Alert Coordination',
        notes: 'STORM-ALERT: Active vehicle rerouting during squall',
      },
      {
        id: 'pn-3',
        date: '2024-10-06',
        startTime: '18:00',
        endTime: '22:00',
        duration: 4.0,
        project: 'VIP Courier Manifest Sync',
        notes: 'CLIENT-VIP: On-demand flight manifest courier sync',
      },
    ],
  },
  {
    id: 'EMP-10496',
    name: 'Devon Brooks',
    department: 'Warehouse Hub B',
    role: 'Handling Technician',
    status: 'Pending',
    submittedAt: null,
    avatar: 'DB',
    entries: [
      {
        id: 'db-1',
        date: '2024-10-01',
        startTime: '18:00',
        endTime: '21:00',
        duration: 3.0,
        project: 'Section D Racking Reorganization',
        notes: 'STAG-REORG: Section D racking reallocation',
      },
    ],
  },
];

export const PROJECT_OPTIONS = [
  'Core Banking Migration',
  'Incident Hotfix L2',
  'E-Commerce Checkout Revamp',
  'Weekend Deployment Standby',
  'Regulatory Audit Compliance Logs',
  'Warehouse Logistics System',
  'Quarterly Inventory Audit',
  'Emergency Dispatch Routing',
  'VIP Courier Manifest Sync',
  'Fleet Safety Inspection Standby',
];
